### ISSUE TITLE
Qt 什么版本阿 报错

### ISSUE THREAD

**Issue by 156631890** [wentaojia2014/TableEdit#2]
2019-11-07 17:10:33 qrc:/Qml/Main.qml:1:1: module "QtQuick" version 2.7 is not installed

我的版本
Qt Creator 4.0.3
Based on Qt 5.6.1 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit)

**Comment by 156631890** [comment]
我的版本太低了吗，涛哥这个要什么版本阿

**Comment by jaredtao** [comment]
5.9以上。都不看README的吗
